server:
  port: 9041
spring:
  application:
    # 指定服务名称  注意:服务名不能出现下划线  默认服务名不区分大小写  推荐服务名大写
    name: CONFIG-CLIENT
  cloud:
    consul:
      host: 121.43.190.195
      port: 8500
      discovery:
        service-name: ${spring.application.name} # 执行注册当前服务的服务名称 默认: ${spring.application.name}
        heartbeat:
          enabled: true
        prefer-ip-address: true

# 指定环境配置
spring:
  profiles: 
    active: dev
